name: TEST_COMPONENT

on:
  workflow_run:
    workflows: 
      - MAIN_PULL_REQUEST
    types: 
      - completed

jobs:
  pr-success:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs: 
      pr_id: ${{ steps.pr.outputs.id }}
    steps:
      - name: Download pr id
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-id
          
      - name: Set pr id
        id : pr
        run: echo "id=$(cat pr-id.txt)" >> $GITHUB_OUTPUT

  tdesign-vue:
    if: github.event.workflow_run.conclusion == 'success'
    needs: pr-success
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tdesign-vue
        uses: actions/checkout@v4
        with:
          repository: Tencent/tdesign-vue

      - name: Checkout tdesign-common
        uses: actions/checkout@v4
        with:
          path: src/_common
          ref: refs/pull/${{ needs.pr-success.outputs.pr_id }}/head

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  tdesign-vue-next:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: pr-success
    steps:
      - name: Checkout tdesign-vue-next
        uses: actions/checkout@v4
        with:
          repository: Tencent/tdesign-vue-next

      - name: Checkout tdesign-common
        uses: actions/checkout@v4
        with:
          path: packages/common
          ref: refs/pull/${{ needs.pr-success.outputs.pr_id }}/head

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - run: pnpm install  --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build

  tdesign-react:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: pr-success
    steps:
      - name: Checkout tdesign-react
        uses: actions/checkout@v4
        with:
          repository: Tencent/tdesign-react

      - name: Checkout tdesign-common
        uses: actions/checkout@v4
        with:
          path: src/_common
          ref: refs/pull/${{ needs.pr-success.outputs.pr_id }}/head

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  tdesign-web-components:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: pr-success
    steps:
      - name: Checkout tdesign-web-components
        uses: actions/checkout@v4
        with:
          repository: TDesignOteam/tdesign-web-components

      - name: Checkout tdesign-common
        uses: actions/checkout@v4
        with:
          path: src/_common
          ref: refs/pull/${{ needs.pr-success.outputs.pr_id }}/head

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  tdesign-mobile-vue:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: pr-success
    steps:
      - name: Checkout tdesign-mobile-vue
        uses: actions/checkout@v4
        with:
          repository: Tencent/tdesign-mobile-vue

      - name: Checkout tdesign-common
        uses: actions/checkout@v4
        with:
          path: src/_common
          ref: refs/pull/${{ needs.pr-success.outputs.pr_id }}/head

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  tdesign-mobile-react:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    needs: pr-success
    steps:
      - name: Checkout tdesign-mobile-react
        uses: actions/checkout@v4
        with:
          repository: Tencent/tdesign-mobile-react

      - name: Checkout tdesign-common
        uses: actions/checkout@v4
        with:
          path: src/_common
          ref: refs/pull/${{ needs.pr-success.outputs.pr_id }}/head

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

